# -*- coding: utf-8 -*-
"""Basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ihCBCWlbCko5X71ogs8AdiSsdn61iI5g
"""

import random
#00
# Write a simple joke bot. The bot starts by asking the user what they want.However,your program will only respond to one response: Joke.
# If the user enters joke then we will put out a single joke. Each time the joke is always the same.


PROMPT = "What do you want?"
JOKE = """Here is a joke for you!
A programmer is heading out to buy groceries.
He tells his assistant: Get a dozen eggs and if they have milk, grab 5 litres.
The assistant returns with 5 dozen eggs and 5 litres of milk.
The programmers asks: Why did you get 5 dozen eggs?
The assistant replies: 'Because they had milk!    """
SORRY = "Sorry i only tells jokes"


def main():

# user se input lena
   user_input = input(PROMPT)

   if user_input == 'joke':
    print(JOKE)
   else:
    print(SORRY)



# 01
# Write a program that asks a user to enter a number. Your program will then double that number and print out the result.
#  It will repeat that process until the value is 100 or greater.

def main_two():
  number  = int(input("Enter a number:"))

  while number <= 100:
    number *= 2
    print("Doubled number: ", number)

  print("Final number is 100 or greater.", number)

#02
# Write a program that prints out the calls for for a spaceship that is about to launch.Countdown from 10 to 1 and then output Liftoff!


def count_down():
  for i in range(10,0, -1):
    print(i)

  print("liftoff!")


# 03
# Guess my number.

def main_three():
  secret_number : int = random.randint(1,99)

  print("I am thinking of a number between 1 and 99...")

  guess = int(input("Enter a guess:"))
  while guess != secret_number:
    if guess < secret_number:
      print("Your guess is too low.")

    else:
      print("Your guess is too high")

    print()
    guess:  int = int(input("Enter a new guess:"))

  print(f"Congrats! The number was: {secret_number}")


# 04
# Print 10 random numbers in range 1 to 100:


N_NUMBERS : int = 10
MIN_VALUE : int = 1
MAX_VALUE : int = 100

def main_four():
  for _ in range(10):
    print(random.randint(1,100))



if __name__ == '__main__':
    main()
    main_two()
    count_down()
    main_three()
    main_four()