# -*- coding: utf-8 -*-
"""BMI_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BCRdKR1IOZ98tVJ1IoimeJHbALqHgBp4
"""

def calculate_bmi(weight,height):
  bmi = weight / (height ** 2)
  return bmi

def bmi_category(bmi):
  if bmi < 18.5:
    return "Underweight"
  elif bmi >= 18.5 and bmi < 25:
    return "Normal weight"
  elif bmi >= 25 and bmi < 30:
    return "Overweight"
  else:
    return "Obese"

weight = float(input("Enter your weight in kilograms: "))
height = float(input("Enter your height in meters: "))

bmi = calculate_bmi(weight, height)

print(f"Your BMI is: {bmi:.2f}")

category = bmi_category(bmi)

print(f"Your BMI category is: {category}")