# -*- coding: utf-8 -*-
"""countdownTimer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ayejk8N5Mb37m91C1mWEUaE_JfQQ9rtN
"""



"""A Countdown Timer is a simple yet useful project in Python that helps in setting a timer for a specific duration (in minutes and seconds). Once the timer starts, it counts down to zero, showing the remaining time, and notifies the user when the timer reaches zero. This is a great way to practice basic Python skills like working with loops, time delays, and user input."""

import time

# Function to start the countdown timer
def countdown_timer(minutes, seconds):
    total_seconds = minutes * 60 + seconds  # Convert total time into seconds

    # Loop until the timer reaches zero
    while total_seconds > 0:
        # Calculate minutes and seconds
        mins, secs = divmod(total_seconds, 60)
        time_left = f'{mins:02}:{secs:02}'  # Format as MM:SS

        # Display the remaining time
        print(f"Time left: {time_left}", end="\r")

        # Wait for 1 second before updating the time
        time.sleep(1)

        # Decrease the total seconds by 1
        total_seconds -= 1

    # When the countdown reaches zero
    print("Time's up! \a")  # \a is an ASCII bell character to alert the user

# Function to get user input for the timer duration
def get_timer_input():
    while True:
        try:
            minutes = int(input("Enter minutes: "))
            seconds = int(input("Enter seconds: "))

            if minutes < 0 or seconds < 0 or seconds >= 60:
                print("Invalid input. Please enter valid minutes and seconds.")
                continue

            return minutes, seconds
        except ValueError:
            print("Invalid input. Please enter numeric values.")

# Main function to run the countdown timer
def main():
    print("Welcome to the Countdown Timer!")
    minutes, seconds = get_timer_input()
    countdown_timer(minutes, seconds)

# Run the countdown timer
main()