# -*- coding: utf-8 -*-
"""Mad_libs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z16tLTSmNCrhOn_ITPTHrXsGgNQr1w_9
"""

# Mad Libs Game

# Story with placeholders
story = """
Once upon a time, a(n) {adjective} {noun} decided to {verb} to the {place}.
Along the way, they met a(n) {animal} who was looking for a {noun2}.
Together, they {verb2} until they reached their destination.
It was a {adjective2} adventure, full of {plural_noun} and surprises!
"""

# Ask user for input
adjective = input("Enter an adjective: ")
noun1 = input("Enter a noun: ")
verb1 = input("Enter a verb: ")
place = input("Enter a place: ")
animal = input("Enter an animal: ")
noun2 = input("Enter a noun: ")
verb2 = input("Enter a verb: ")
adjective2 = input("Enter an adjective: ")
plural_noun = input("Enter a plural noun: ")

# Fill in the blanks with the user's input
mad_lib = story.format(adjective=adjective, noun=noun1, verb=verb1, place=place,
animal=animal, noun2=noun2, verb2=verb2, adjective2=adjective2,
plural_noun=plural_noun)

# Print the final Mad Lib story
print("\nHere is your Mad Lib story:")
print(mad_lib)

