# -*- coding: utf-8 -*-
"""project_3_guessTheNumber_user.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16RGeTFOr5k-nSTHWLMGOHcwyCzfo5sEq
"""

import random
def guess_the_number():
  number = random.randint(1,100)
  attempts = 0
  print("Welcome to the guess the Number Game")
  print("I have selected a number between 1 and 100. Can you guess it?")
  print("Try to guess it.")

  while True:
    guess = int(input("Enter your guess"))
    attempts += 1
    if guess < number:
      print("Too low try again")
    elif guess > number:
      print("Too high try again")
    else:
      print(f"Congratulations! You guessed the number {number} in {attempts} attempts.")
      break
guess_the_number()