# -*- coding: utf-8 -*-
"""project4_Rock_Paper_scissor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zXXlLs0jPkyaIPAL9HfakdaCXnl9HjDd
"""

import random

# Function to get the winner
def determine_winner(user_choice, computer_choice):
    if user_choice == computer_choice:
        return "It's a tie!"

    if (user_choice == "rock" and computer_choice == "scissors") or \
       (user_choice == "scissors" and computer_choice == "paper") or \
       (user_choice == "paper" and computer_choice == "rock"):
        return "You win!"

    return "Computer wins!"

# Function for the game
def rock_paper_scissors():
    # List of possible choices
    choices = ["rock", "paper", "scissors"]

    print("Welcome to Rock, Paper, Scissors Game!")

    while True:
        # User input
        user_choice = input("Enter your choice (rock, paper, or scissors): ").lower()

        if user_choice not in choices:
            print("Invalid input! Please enter 'rock', 'paper', or 'scissors'.")
            continue

        # Computer input (random choice)
        computer_choice = random.choice(choices)
        print(f"Computer chose: {computer_choice}")

        # Determine the winner
        result = determine_winner(user_choice, computer_choice)
        print(result)

        # Ask if the user wants to play again
        play_again = input("Do you want to play again? (yes/no): ").lower()

        if play_again != "yes":
            print("Thank you for playing! Goodbye!")
            break

# Run the game
rock_paper_scissors()