# -*- coding: utf-8 -*-
"""project2_guessTheNumber_computer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rBxZYDn79da6EpoFSjkk837Omtge0sYG
"""

import random

def guess_the_number():
    # Step 1: Generate a random number between 1 and 100
    number_to_guess = random.randint(1, 100)

    # Step 2: Introduce the game
    print("Welcome to the Guess the Number Game!")
    print("I am thinking of a number between 1 and 100. Can you guess it?")

    # Step 3: Initialize variables
    attempts = 0
    guess = None

    # Step 4: Game loop
    while guess != number_to_guess:
        try:
            # Get user input
            guess = int(input("Enter your guess: "))
            attempts += 1

            # Provide feedback
            if guess < number_to_guess:
                print("Too low! Try again.")
            elif guess > number_to_guess:
                print("Too high! Try again.")
            else:
                print(f"Congratulations! You've guessed the number {number_to_guess} in {attempts} attempts.")
                break  # Exit the loop when the correct number is guessed
        except ValueError:
            print("Please enter a valid number.")

# Run the game
guess_the_number()